server:
  port: 8080

llm:
  api:
    url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
    key: sk-ee6d5135c56543ccb3cd36c80a98bf87
  model: qwen-plus
  top_n: 5

okhttp:
  connect-timeout: 10000
  read-timeout: 20000
  write-timeout: 20000
  retry-on-connection-failure: true
  max-idle-connections: 5
  keep-alive-duration: 300000

# Knowledge file location (external override possible)
kb:
  auto-approve-threshold: 0.9   # >= 此置信度将自动通过并写入 kb_info
  auto-approve-enabled: true
  auto-approve-top-n: 50         # 如果你用 TopN 策略，可限制每次自动审核数量


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.133:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      connection-timeout: 30000 # 连接超时时间，单位毫秒
      minimum-idle: 5           # 最小空闲连接数
      maximum-pool-size: 20     # 最大连接池大小
      idle-timeout: 600000      # 空闲连接超时时间，单位毫秒
      max-lifetime: 1800000     # 连接最大生命周期，单位毫秒
      pool-name: HikariPool     # 连接池名称
      connection-test-query: select 1
  jackson:
    time-zone: GMT+8


# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aiassistant
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

